### ISSUE TITLE
Marathon app config

### ISSUE THREAD

**Issue by powellchristoph** [ekesken/docker-rabbitmq#1]
I am just diving into Mesos/Marathon/Docker and your docker image is great. I would love to see the app's json mesos configuration if possible.

**Comment by ekesken** [comment]
I added an example marathon config to README. Please be aware of issue #2 and #3, I don't have chance to update and test image nowadays, please send me a pull request if you fix any of these problems.

**Comment by powellchristoph** [comment]
Perfect, thanks!
