### ISSUE TITLE
Node discovery is done too early and other nodes are not found

### ISSUE THREAD

**Issue by teelahti** [ekesken/docker-rabbitmq#5]
Currently the bootstrapper file rabbitmq-cluster.py searches for other nodes by queruing Marathon tasks whose createdAt is not null. This does not work correctly when the service is pushed to Marathon, as both nodes are in staging state and thus don't find each others.

**Comment by ekesken** [comment]
I made it wait for all tasks to start, before doing any configuration, this should solve the problem, can you try to repeat it?
